### ISSUE TITLE
Error when executing snakemake

### ISSUE THREAD

**Issue by retrorna** [maxfieldk/TE-Seq#6]
Hi,

I tried to execute the pipeline through snakemake but immediately run into an error:

```
snakemake --cores 10
Assuming unrestricted shared filesystem usage.
host: clip-c2-76.cbe.vbc.ac.at
Building DAG of jobs...
InputFunctionException in rule aref_merge_rm_out_wholegenome in file "/TEseq/TE-Seq/workflow/aref/snakefile", line 1148:
Error:
  WorkflowError:
    Missing wildcard values for sample_or_ref, default_or_extended
Wildcards:

Traceback:
 (rule aref_merge_rm_out_wholegenome, line 2306, /TEseq/TE-Seq/workflow/aref/snakefile)
```

Any ideas?

**Comment by maxfieldk** [comment]
Hi @retrorna ! 
Thank you for raising this bug - I've pushed what should be a fix to the stable branch. 
Hopefully once you
"git pull"
and try again, all will work.
Please let me know if you encounter any other issues!

**Comment by retrorna** [comment]
Re-ran it and now getting an error with loading environments I think

```
/usr/bin/bash: line 1: fastp: command not found
RuleException:
CalledProcessError in file "/TESeq/myproject/TE-Seq/workflow/srna/snakefile", line 194:
Command 'set -euo pipefail;  
fastp -i srna_rawdata/346054_S46_R1_001.fastq.gz -I srna_rawdata/346054_S46_R2_001.fastq.gz -o srna/outs/sampl4/trimmedReads/sampl4_1.trimmed.fastq.gz -O srna/outs/sampl4/trimmedReads/sampl4_2.trimmed.fastq.gz --json srna/outs/sampl4/trimmedReads/fastp.json --html srna/outs/sampl4/trimmedReads/fastp.html --detect_adapter_for_pe --thread 6' returned non-zero exit status 127.
[Mon Jun  2 10:09:15 2025]
Error in rule srna_fastp_PE:
    message: None
    jobid: 92
    input: srna_rawdata/346054_S46_R1_001.fastq.gz, srna_rawdata/346054_S46_R2_001.fastq.gz
    output: srna/outs/sampl4/trimmedReads/sampl4_1.trimmed.fastq.gz, srna/outs/sampl4/trimmedReads/sampl4_2.trimmed.fastq.gz, srna/outs/sampl4/trimmedReads/fastp.json, srna/outs/sampl4/trimmedReads/fastp.html
    shell:
        
fastp -i srna_rawdata/346054_S46_R1_001.fastq.gz -I srna_rawdata/346054_S46_R2_001.fastq.gz -o srna/outs/sampl4/trimmedReads/sampl4_1.trimmed.fastq.gz -O srna/outs/sampl4/trimmedReads/sampl4_2.trimmed.fastq.gz --json srna/outs/sampl4/trimmedReads/fastp.json --html srna/outs/sampl4/trimmedReads/fastp.html --detect_adapter_for_pe --thread 6
        
        (command exited with non-zero exit code)

[Mon Jun  2 10:09:15 2025]
localrule pull_tetranscripts_container:
    output: containers/tetranscripts:2.2.3.sif
    jobid: 185
    reason: Missing output files: containers/tetranscripts:2.2.3.sif
    resources: tmpdir=/tmp, cpus_per_task=4, runtime=200, mem_mb=100000, mem_mib=95368

[Mon Jun  2 10:09:15 2025]
Finished jobid: 8 (Rule: aref_copySelectAnnotations)
1 of 225 steps (0.4%) done
WorkflowError:
Error exporting conda environment --name 'qc':
/usr/bin/bash: line 10: __conda_exe: command not found
```

**Comment by maxfieldk** [comment]
I suspect you may have called snakemake without the --profile workflow/profile/default option, which enables snakemake rules to run in containers. Is that the issue? Also go ahead and run another "git pull" before continuing - I pushed a couple QOL improvements over the past 24 hours.

**Comment by retrorna** [comment]
Hey,

now the pipeline runs but jobs related to aligning seem to fail. 

```
Error in rule srna_mycoplasmaCheck:
    message: SLURM-job '18173934' failed, SLURM status is: 'FAILED'. For further error details see the cluster/cloud log and the log files of the involved rule(s).
    jobid: 217
    input: srna/outs/sample2/trimmedReads/sample2.trimmed.fastq.gz
    output: srna/qc/mycoplasma/mycoplasmasample2.sorted.bam
    log: /myproject/TE-Seq/.snakemake/slurm_logs/rule_srna_mycoplasmaCheck/sample2/18173934.log (check log file(s) for error details)
    conda-env: omics
    shell:
        
mkdir -p $(dirname srna/qc/mycoplasma/mycoplasmasample2.sorted.bam)
bowtie2 --threads 10 -x resources/genomes/mycoplasma/mycoplasma_index -U srna/outs/sample2/trimmedReads/sample2.trimmed.fastq.gz | samtools view -@8 -bS - > srna/qc/mycoplasma/mycoplasmasample2.sorted.bam.temp
samtools sort -@8 -m4g srna/qc/mycoplasma/mycoplasmasample2.sorted.bam.temp > srna/qc/mycoplasma/mycoplasmasample2.sorted.bam
rm srna/qc/mycoplasma/mycoplasmasample2.sorted.bam.temp
samtools index  -@6 srna/qc/mycoplasma/mycoplasmasample2.sorted.bam 
samtools idxstat -@6 srna/qc/mycoplasma/mycoplasmasample2.sorted.bam 
samtools stats srna/qc/mycoplasma/mycoplasmasample2.sorted.bam > srna/qc/mycoplasma/mycoplasmasample2.sorted.bam.stats.txt
        
        (command exited with non-zero exit code)
    external_jobid: 18173934
Trying to restart job 217.
Select jobs to execute...
Execute 1 jobs...
```

Any pointers on how to trouble shoot this now? All containers are installed locally and in config paths are referenced 
```

containers:
  teseq:
    use_preexisting_response: "yes"
    path: "/resources/containers/te-seq_v1.3.sif"
  tetools:
    use_preexisting_response: "yes"
    path: "/resources/containers/tetools_1.88.5.sif"
  gatk:
    use_preexisting_response: "yes"
    path: "/resources/containers/gatk_4.6.1.0.sif"
  pepper_deepvariant:
    use_preexisting_response: "yes"
    path: "/resources/containers/pepper_deepvariant_r0.8.sif"
  dorado:
    use_preexisting_response: "yes"
    path: "/resources/containers/dorado_sha268dcb4cd02093e75cdc58821f8b93719c4255ed.sif"
  tetranscripts:
    use_preexisting_response: "yes"
    path: "/resources/containers/tetranscripts_v2.2.3.sif"
```
